version: "3.7"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=valeriopwd
      - POSTGRES_USER=valerio.mellini@gmail.com
      - POSTGRES_DB=pgdb

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=valerio.mellini@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=valeriopwd


  