#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 28 10:18:19 2021

@author: valeriomellini
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import yfinance as yf

from waccpy import calculateWacc

def calculateDCF(company):
    pass

def linear_regression_model(Y):
    X = np.array([i for i in range (0,len(Y))]).reshape(-1,1)
    Y = np.array(Y)
    lm = LinearRegression()
    lm.fit(X, Y)
    return (lm.intercept_, lm.coef_)

def extract_fcf(n):
    pass

def getFrehCashFlow(company, secretkey):
    cash_flow = requests.get(f'https://financialmodelingprep.com/api/v3/cash-flow-statement/{company}?apikey={secretkey}').json()
    #freeCashFlow
    len_cash_flow = len(cash_flow)
    if len > 5:
        extract_fcf(5)
    else:
        extract_fcf(len_cash_flow)