version: "3.7"

services:

  microflask:
    build: ./microflask
    container_name: microflask
    restart: always
    environment:
      - APP_NAME=BFF
    expose:
      - 6001

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - microflask
  
